name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:v1.2.0
    steps:
    - name: Install dependencies
      run: |
        apk add build-base git zip
        apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/v3.12/testing ccze

    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow

    - name: Install ps2eth
      run: |
        git clone https://github.com/ps2dev/ps2eth.git
        cd ps2eth && make clean all install

    - name: Install smb2
      run: |
        git clone https://github.com/sahlberg/libsmb2
        cd libsmb2/lib && make -f Makefile.PS2_EE clean
        make -f Makefile.PS2_EE install | ccze

    - name: Compile wLaunchELF
      run: |
        make | ccze
    
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: wLaunchELF-${{ steps.slug.outputs.sha8 }}
        path: BOOT.ELF

    - name: Create release
      if: github.ref == 'refs/heads/master'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Latest development build"
        files: BOOT.ELF
